[2024-05-18T19:01:04.486+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [queued]>
[2024-05-18T19:01:04.583+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [queued]>
[2024-05-18T19:01:04.644+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T19:01:04.660+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-05-18T19:01:04.674+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T19:01:04.921+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): github> on 2024-05-18 17:54:45.547450+00:00
[2024-05-18T19:01:04.966+0000] {standard_task_runner.py:55} INFO - Started process 7226 to run task
[2024-05-18T19:01:05.036+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'assignment_dag', 'github', 'manual__2024-05-18T17:54:45.547450+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/assignment_dag.py', '--cfg-path', '/tmp/tmpndtdan95']
[2024-05-18T19:01:05.055+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask github
[2024-05-18T19:01:05.634+0000] {task_command.py:376} INFO - Running <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [running]> on host ec7a58f0c94e
[2024-05-18T19:01:06.499+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=i200704@nu.edu.pk
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment_dag
AIRFLOW_CTX_TASK_ID=github
AIRFLOW_CTX_EXECUTION_DATE=2024-05-18T17:54:45.547450+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-18T17:54:45.547450+00:00
[2024-05-18T19:01:06.536+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-18T19:01:06.548+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "\n    cd $(dirname /opt/***/output.csv) &&     git add .dvc/config output.csv.dvc .gitignore &&     git diff --staged --quiet || git commit -m 'Add DVC files' &&     git push -u origin main\n    "]
[2024-05-18T19:01:06.638+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T19:01:06.679+0000] {subprocess.py:93} INFO - /bin/bash: line 2: git: command not found
[2024-05-18T19:01:06.686+0000] {subprocess.py:93} INFO - /bin/bash: line 2: git: command not found
[2024-05-18T19:01:06.689+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-18T19:01:06.818+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-18T19:01:06.881+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=assignment_dag, task_id=github, execution_date=20240518T175445, start_date=20240518T190104, end_date=20240518T190106
[2024-05-18T19:01:07.033+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task github (Bash command failed. The command returned a non-zero exit code 127.; 7226)
[2024-05-18T19:01:07.113+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-18T19:01:07.267+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
