[2024-05-18T18:55:54.177+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [queued]>
[2024-05-18T18:55:54.360+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [queued]>
[2024-05-18T18:55:54.365+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T18:55:54.371+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-05-18T18:55:54.375+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-18T18:55:54.506+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): github> on 2024-05-18 17:54:45.547450+00:00
[2024-05-18T18:55:54.530+0000] {standard_task_runner.py:55} INFO - Started process 7085 to run task
[2024-05-18T18:55:54.590+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'assignment_dag', 'github', 'manual__2024-05-18T17:54:45.547450+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/assignment_dag.py', '--cfg-path', '/tmp/tmpbqm7n7t6']
[2024-05-18T18:55:54.600+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask github
[2024-05-18T18:55:55.489+0000] {task_command.py:376} INFO - Running <TaskInstance: assignment_dag.github manual__2024-05-18T17:54:45.547450+00:00 [running]> on host ec7a58f0c94e
[2024-05-18T18:55:56.533+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=i200704@nu.edu.pk
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment_dag
AIRFLOW_CTX_TASK_ID=github
AIRFLOW_CTX_EXECUTION_DATE=2024-05-18T17:54:45.547450+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-18T17:54:45.547450+00:00
[2024-05-18T18:55:56.590+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-18T18:55:56.633+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "\n    cd $(dirname /opt/***/output.csv) &&     git add .dvc/config output.csv.dvc .gitignore &&     git diff --staged --quiet || git commit -m 'Add DVC files' &&     git push -u origin main\n    "]
[2024-05-18T18:55:56.738+0000] {subprocess.py:86} INFO - Output:
[2024-05-18T18:55:56.834+0000] {subprocess.py:93} INFO - /bin/bash: line 2: git: command not found
[2024-05-18T18:55:56.898+0000] {subprocess.py:93} INFO - /bin/bash: line 2: git: command not found
[2024-05-18T18:55:56.933+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-18T18:55:57.080+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-18T18:55:57.136+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=assignment_dag, task_id=github, execution_date=20240518T175445, start_date=20240518T185554, end_date=20240518T185557
[2024-05-18T18:55:57.421+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task github (Bash command failed. The command returned a non-zero exit code 127.; 7085)
[2024-05-18T18:55:57.528+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-18T18:55:57.951+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
